# Generated by Django 3.0.3 on 2020-02-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True, max_length=500)),
                ('experience', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('skills_required', models.CharField(blank=True, max_length=100)),
                ('modules', models.CharField(blank=True, max_length=100)),
                ('projects', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Career')),
            ],
        ),
    ]
