"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR =  os.path.join(BASE_DIR,'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-&c^i#uesf3hj=a-5obmi3)h&e8(=^mny@1e6wrgl(3^gu+)eu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',

    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_cleanup',
    #all auth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    #django-notifications-hq
    'notifications',

    #ckeditor
    'ckeditor',
    'ckeditor_uploader',
    #installed apps
    'contact',
    'careers',
    #installed using pip
    'crispy_forms',
    'widget_tweaks',
    #for mail queue
    'mailer',

]
#CKEDITOR

CKEDITOR_UPLOAD_PATH    =   'uploads/'

CKEDITOR_CONFIGS = {
    'default': {
        # 'toolbar': 'Custom',
        'width': 'auto',
        'height': 'auto',
        'background':'black',
        # 'toolbar_Custom': [
        #     ['Bold', 'Italic', 'Underline'],
        #     ['NumberedList', 'BulletedList'],
        # ],
        'toolbarLocation' : 'bottom',  
        'uiColor' : '#f5f7f9',
        'borderWidth':'0px',
        'filebrowserBrowseUrl':'',
        
 
        
    }
}
#all auth
SITE_ID = 1
#User profile
AUTH_PROFILE_MODULE = 'userprofile.UserProfile'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': '****',
#         'USER': 'postgres',
#         'PASSWORD': '*****',
#         'HOST': '****',
#         'PORT': '****',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
        # `allauth` specific authentication methods, such as login by e-mail
   
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static"),
# ]
# STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR))
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# to store data 
MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR,'files')

#allauth redirect
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL='/'




#for django mailer
EMAIL_BACKEND = "mailer.backend.DbBackend"

#telling django mailer to how to actually send the mail
MAILER_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST = '***********************'
EMAIL_PORT = '***'
EMAIL_HOST_USER = '***********************'
EMAIL_HOST_PASSWORD = '***********************'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




ROOT_URLCONF = 'project.urls'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#20 mins
SESSION_COOKIE_AGE = 120*60
